### ISSUE TITLE
Exception caught by rendering library: Build scheduled during frame

### ISSUE THREAD

**Issue by ngoctranfire** [fayeed/dash_chat#68]
Although there is no crash, I think there is inherently wrong with what is going on with the widget.  When ever I press the "send" in the keyboard button, this error occurs.

**To Reproduce**
1. Create a Dash Chat View.
2. Compose a message. Then use the Keyboard's send button.
3. Notice that the error occurs.
4. Here's the error:
```
While the widget tree was being built, laid out, and painted, a new frame was scheduled to rebuild the widget tree.

This might be because setState() was called from a layout or paint callback. If a change is needed to the widget tree, it should be applied as the tree is being built. Scheduling a change for the subsequent frame instead results in an interface that lags behind by one frame. If this was done to make your build dependent on a size measured at layout time, consider using a LayoutBuilder, CustomSingleChildLayout, or CustomMultiChildLayout. If, on the other hand, the one frame delay is the desired effect, for example because this is an animation, consider scheduling the frame in a post-frame callback using SchedulerBinding.addPostFrameCallback or using an AnimationController to trigger the animation.

The relevant error-causing widget was: 
  DashChat-[LabeledGlobalKey<DashChatState>#67918] file:///Users/ngoctranfire/Desktop/Flutter-Apps/alike_dating/lib/views/chat/user_matches_chat.dart:78:20
When the exception was thrown, this was the stack: 
#0      WidgetsBinding._handleBuildScheduled.<anonymous closure> (package:flutter/src/widgets/binding.dart:648:9)
#1      WidgetsBinding._handleBuildScheduled (package:flutter/src/widgets/binding.dart:671:6)
#2      BuildOwner.scheduleBuildFor (package:flutter/src/widgets/framework.dart:2316:7)
#3      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:3915:11)
#4      State.setState (package:flutter/src/widgets/framework.dart:1168:14)
...
The following RenderObject was being processed when the exception was fired: RenderShrinkWrappingViewport#289e0 relayoutBoundary=up14 NEEDS-PAINT
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(0.0<=w<=401.4, 0.0<=h<=636.6)
...  layer: OffsetLayer#11540 DETACHED
...    offset: Offset(0.0, 0.0)
...  size: Size(401.4, 354.6)
...  axisDirection: down
...  crossAxisDirection: right
...  offset: ScrollPositionWithSingleContext#7c04b(offset: 2481.4, range: 0.0..2199.4, viewport: 636.6, ScrollableState, ClampingScrollPhysics, BallisticScrollActivity#abb33(AnimationController#47f08(▶ 2481.429; for BallisticScrollActivity)), ScrollDirection.idle)
RenderObject: RenderShrinkWrappingViewport#289e0 relayoutBoundary=up14 NEEDS-PAINT
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(0.0<=w<=401.4, 0.0<=h<=636.6)
  layer: OffsetLayer#11540 DETACHED
    offset: Offset(0.0, 0.0)
  size: Size(401.4, 354.6)
  axisDirection: down
  crossAxisDirection: right
  offset: ScrollPositionWithSingleContext#7c04b(offset: 2481.4, range: 0.0..2199.4, viewport: 636.6, ScrollableState, ClampingScrollPhysics, BallisticScrollActivity#abb33(AnimationController#47f08(▶ 2481.429; for BallisticScrollActivity)), ScrollDirection.idle)
...  child 0: RenderSliverPadding#72a14 relayoutBoundary=up15 NEEDS-PAINT
...    needs compositing
...    parentData: layoutOffset=0.0 (can use size)
...    constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 2481.4, remainingPaintExtent: 636.6, crossAxisExtent: 401.4, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 636.6, remainingCacheExtent: 1136.6 cacheOrigin: -250.0 )
...    geometry: SliverGeometry(scrollExtent: 2836.0, paintExtent: 354.6, maxPaintExtent: 2836.0, hasVisualOverflow: true, cacheExtent: 604.6)
...      scrollExtent: 2836.0
...      paintExtent: 354.6
...      maxPaintExtent: 2836.0
...      hasVisualOverflow: true
...      cacheExtent: 604.6
...    padding: EdgeInsets.zero
...    textDirection: ltr
...    child: RenderSliverList#b1ef3 relayoutBoundary=up16 NEEDS-PAINT
...      needs compositing
...      parentData: paintOffset=Offset(0.0, 0.0) (can use size)
...      constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 2481.4, remainingPaintExtent: 636.6, crossAxisExtent: 401.4, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 636.6, remainingCacheExtent: 1136.6 cacheOrigin: -250.0 )
...      geometry: SliverGeometry(scrollExtent: 2836.0, paintExtent: 354.6, maxPaintExtent: 2836.0, hasVisualOverflow: true, cacheExtent: 604.6)
...        scrollExtent: 2836.0
...        paintExtent: 354.6
...        maxPaintExtent: 2836.0
...        hasVisualOverflow: true
...        cacheExtent: 604.6
...      currently live children: 33 to 44
...      child with index 33: RenderIndexedSemantics#ec7ab relayoutBoundary=up17 NEEDS-PAINT
...        needs compositing
...        parentData: index=33; layoutOffset=2134.0 (can use size)
...        constraints: BoxConstraints(w=401.4, 0.0<=h<=Infinity)
...        semantic boundary
...        size: Size(401.4, 98.0)
...        index: 33
...        child: RenderRepaintBoundary#a3031 relayoutBoundary=up18 NEEDS-PAINT
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=401.4, 0.0<=h<=Infinity)
...          layer: OffsetLayer#96998 DETACHED
...            offset: Offset(0.0, -17.8)
...          size: Size(401.4, 98.0)
...          metrics: 99.2% useful (1 bad vs 119 good)
...          diagnosis: this is an outstandingly useful repaint boundary and should definitely be kept
...      child with index 34: RenderIndexedSemantics#17bcb relayoutBoundary=up17
...        needs compositing
...        parentData: index=34; layoutOffset=2232.0 (can use size)
...        constraints: BoxConstraints(w=401.4, 0.0<=h<=Infinity)
...        semantic boundary
...        size: Size(401.4, 54.0)
...        index: 34
...        child: RenderRepaintBoundary#6083f relayoutBoundary=up18
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=401.4, 0.0<=h<=Infinity)
...          layer: OffsetLayer#72ae4 DETACHED
...            offset: Offset(0.0, -51.1)
...          size: Size(401.4, 54.0)
...          metrics: 99.3% useful (1 bad vs 135 good)
...          diagnosis: this is an outstandingly useful repaint boundary and should definitely be kept
...      child with index 35: RenderIndexedSemantics#914ea relayoutBoundary=up17
...        needs compositing
...        parentData: index=35; layoutOffset=2286.0 (can use size)
...        constraints: BoxConstraints(w=401.4, 0.0<=h<=Infinity)
...        semantic boundary
...        size: Size(401.4, 54.0)
...        index: 35
...        child: RenderRepaintBoundary#dd124 relayoutBoundary=up18
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=401.4, 0.0<=h<=Infinity)
...          layer: OffsetLayer#6906b DETACHED
...            offset: Offset(0.0, -34.8)
...          size: Size(401.4, 54.0)
...          metrics: 99.4% useful (1 bad vs 153 good)
...          diagnosis: this is an outstandingly useful repaint boundary and should definitely be kept
...      child with index 36: RenderIndexedSemantics#da8e2 relayoutBoundary=up17
...        needs compositing
...        parentData: index=36; layoutOffset=2340.0 (can use size)
...        constraints: BoxConstraints(w=401.4, 0.0<=h<=Infinity)
...        semantic boundary
...        size: Size(401.4, 54.0)
...        index: 36
...        child: RenderRepaintBoundary#c7eea relayoutBoundary=up18
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=401.4, 0.0<=h<=Infinity)
...          layer: OffsetLayer#0ce31 DETACHED
...            offset: Offset(0.0, -52.5)
...          size: Size(401.4, 54.0)
...          metrics: 99.4% useful (1 bad vs 168 good)
...          diagnosis: this is an outstandingly useful repaint boundary and should definitely be kept
...      child with index 37: RenderIndexedSemantics#b24fa relayoutBoundary=up17
...        needs compositing
...        parentData: index=37; layoutOffset=2394.0 (can use size)
...        constraints: BoxConstraints(w=401.4, 0.0<=h<=Infinity)
...        semantic boundary
...        size: Size(401.4, 54.0)
...        index: 37
...        child: RenderRepaintBoundary#f5562 relayoutBoundary=up18
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=401.4, 0.0<=h<=Infinity)
...          layer: OffsetLayer#1e46e DETACHED
...            offset: Offset(0.0, -50.9)
...          size: Size(401.4, 54.0)
...          metrics: 99.5% useful (1 bad vs 206 good)
...          diagnosis: this is an outstandingly useful repaint boundary and should definitely be kept
...      child with index 38: RenderIndexedSemantics#498b1 relayoutBoundary=up17
...        needs compositing
...        parentData: index=38; layoutOffset=2448.0 (can use size)
...        constraints: BoxConstraints(w=401.4, 0.0<=h<=Infinity)
...        semantic boundary
...        size: Size(401.4, 54.0)
...        index: 38
...        child: RenderRepaintBoundary#e867e relayoutBoundary=up18
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=401.4, 0.0<=h<=Infinity)
...          layer: OffsetLayer#2111f DETACHED
...            offset: Offset(0.0, -33.4)
...          size: Size(401.4, 54.0)
...          metrics: 99.6% useful (1 bad vs 237 good)
...          diagnosis: this is an outstandingly useful repaint boundary and should definitely be kept
...      child with index 39: RenderIndexedSemantics#ffc93 relayoutBoundary=up17
...        needs compositing
...        parentData: index=39; layoutOffset=2502.0 (can use size)
...        constraints: BoxConstraints(w=401.4, 0.0<=h<=Infinity)
...        semantic boundary
...        size: Size(401.4, 54.0)
...        index: 39
...        child: RenderRepaintBoundary#6826a relayoutBoundary=up18
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=401.4, 0.0<=h<=Infinity)
...          layer: OffsetLayer#7b76f DETACHED
...            offset: Offset(0.0, 20.6)
...          size: Size(401.4, 54.0)
...          metrics: 99.6% useful (1 bad vs 234 good)
...          diagnosis: this is an outstandingly useful repaint boundary and should definitely be kept
...      child with index 40: RenderIndexedSemantics#d28df relayoutBoundary=up17
...        needs compositing
...        parentData: index=40; layoutOffset=2556.0 (can use size)
...        constraints: BoxConstraints(w=401.4, 0.0<=h<=Infinity)
...        semantic boundary
...        size: Size(401.4, 54.0)
...        index: 40
...        child: RenderRepaintBoundary#2f54f relayoutBoundary=up18
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=401.4, 0.0<=h<=Infinity)
...          layer: OffsetLayer#15e69 DETACHED
...            offset: Offset(0.0, 74.6)
...          size: Size(401.4, 54.0)
...          metrics: 99.6% useful (1 bad vs 229 good)
...          diagnosis: this is an outstandingly useful repaint boundary and should definitely be kept
...      child with index 41: RenderIndexedSemantics#30f60 relayoutBoundary=up17
...        needs compositing
...        parentData: index=41; layoutOffset=2610.0 (can use size)
...        constraints: BoxConstraints(w=401.4, 0.0<=h<=Infinity)
...        semantic boundary
...        size: Size(401.4, 54.0)
...        index: 41
...        child: RenderRepaintBoundary#b9e1a relayoutBoundary=up18
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=401.4, 0.0<=h<=Infinity)
...          layer: OffsetLayer#76c83 DETACHED
...            offset: Offset(0.0, 128.6)
...          size: Size(401.4, 54.0)
...          metrics: 99.6% useful (1 bad vs 223 good)
...          diagnosis: this is an outstandingly useful repaint boundary and should definitely be kept
...      child with index 42: RenderIndexedSemantics#a66fd relayoutBoundary=up17
...        needs compositing
...        parentData: index=42; layoutOffset=2664.0 (can use size)
...        constraints: BoxConstraints(w=401.4, 0.0<=h<=Infinity)
...        semantic boundary
...        size: Size(401.4, 54.0)
...        index: 42
...        child: RenderRepaintBoundary#476bd relayoutBoundary=up18
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=401.4, 0.0<=h<=Infinity)
...          layer: OffsetLayer#27399 DETACHED
...            offset: Offset(0.0, 182.6)
...          size: Size(401.4, 54.0)
...          metrics: 99.5% useful (1 bad vs 202 good)
...          diagnosis: this is an outstandingly useful repaint boundary and should definitely be kept
...      child with index 43: RenderIndexedSemantics#eff65 relayoutBoundary=up17
...        needs compositing
...        parentData: index=43; layoutOffset=2718.0 (can use size)
...        constraints: BoxConstraints(w=401.4, 0.0<=h<=Infinity)
...        semantic boundary
...        size: Size(401.4, 54.0)
...        index: 43
...        child: RenderRepaintBoundary#b8d0c relayoutBoundary=up18
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=401.4, 0.0<=h<=Infinity)
...          layer: OffsetLayer#e54e2 DETACHED
...            offset: Offset(0.0, 236.6)
...          size: Size(401.4, 54.0)
...          metrics: 99.2% useful (1 bad vs 127 good)
...          diagnosis: this is an outstandingly useful repaint boundary and should definitely be kept
...      child with index 44: RenderIndexedSemantics#02e85 relayoutBoundary=up17
...        needs compositing
...        parentData: index=44; layoutOffset=2772.0 (can use size)
...        constraints: BoxConstraints(w=401.4, 0.0<=h<=Infinity)
...        semantic boundary
...        size: Size(401.4, 64.0)
...        index: 44
...        child: RenderRepaintBoundary#b2654 relayoutBoundary=up18
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=401.4, 0.0<=h<=Infinity)
...          layer: OffsetLayer#4bfa5 DETACHED
...            offset: Offset(0.0, 290.6)
...          size: Size(401.4, 64.0)
...          metrics: 98.1% useful (1 bad vs 53 good)
...          diagnosis: this is an outstandingly useful repaint boundary and should definitely be kept
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Desktop (please complete the following information):**
On iOS (Real Device) and Android physical devices, this happens:
Flutter version:
Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287,
    locale en-US)
    • Flutter version 1.12.13+hotfix.9 at /Users/ngoctranfire/flutter
    • Framework revision f139b11009 (4 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

**Additional context**
It seems like this bug is occurring because at the SAME time that the keyboard goes down, the text is being redrawn, which causes this unexpected state.

**Comment by kornha** [comment]
Same error.

**Comment by joseph-jordan** [comment]
Any updates on this?

**Comment by peter-sg** [comment]
I had the same issue and it appears to happen for me in chat_view.dart 

void changeVisible(bool value) {
    if (widget.scrollToBottom) {
      setState(() {
        visible = value;
      });
    }
  }

Here's the call stack: 
```WidgetsBinding._handleBuildScheduled.<anonymous closure> (/Users/Development/flutter/packages/flutter/lib/src/widgets/binding.dart:753)
WidgetsBinding._handleBuildScheduled (/Users/Development/flutter/packages/flutter/lib/src/widgets/binding.dart:776)
BuildOwner.scheduleBuildFor (/Users/Development/flutter/packages/flutter/lib/src/widgets/framework.dart:2511)
Element.markNeedsBuild (/Users/Development/flutter/packages/flutter/lib/src/widgets/framework.dart:4186)
State.setState (/Users/Development/flutter/packages/flutter/lib/src/widgets/framework.dart:1253)
DashChatState.changeVisible (/Users/.pub-cache/hosted/pub.dartlang.org/dash_chat-1.1.13/lib/src/chat_view.dart:382)
_MessageListViewState.scrollNotificationFunc (/Users/.pub-cache/hosted/pub.dartlang.org/dash_chat-1.1.13/lib/src/message_listview.dart:93)
NotificationListener._dispatch (/Users/Development/flutter/packages/flutter/lib/src/widgets/notification_listener.dart:129)
Notification.visitAncestor (/Users/Development/flutter/packages/flutter/lib/src/widgets/notification_listener.dart:47)
ViewportNotificationMixin.visitAncestor (/Users/Development/flutter/packages/flutter/lib/src/widgets/scroll_notification.dart:31)
Element.visitAncestorElements (/Users/Development/flutter/packages/flutter/lib/src/widgets/framework.dart:3989)
Notification.dispatch (/Users/Development/flutter/packages/flutter/lib/src/widgets/notification_listener.dart:63)
ScrollActivity.dispatchScrollStartNotification (/Users/Development/flutter/packages/flutter/lib/src/widgets/scroll_activity.dart:91)
ScrollPosition.didStartScroll (/Users/Development/flutter/packages/flutter/lib/src/widgets/scroll_position.dart:716)
ScrollPosition.beginActivity (/Users/Development/flutter/packages/flutter/lib/src/widgets/scroll_position.dart:708)
ScrollPositionWithSingleContext.beginActivity (/Users/Development/flutter/packages/flutter/lib/src/widgets/scroll_position_with_single_context.dart:116)
ScrollPositionWithSingleContext.goBallistic (/Users/Development/flutter/packages/flutter/lib/src/widgets/scroll_position_with_single_context.dart:148)
IdleScrollActivity.applyNewDimensions (/Users/Development/flutter/packages/flutter/lib/src/widgets/scroll_activity.dart:149)
ScrollPosition.applyNewDimensions (/Users/Development/flutter/packages/flutter/lib/src/widgets/scroll_position.dart:524)
ScrollPositionWithSingleContext.applyNewDimensions (/Users/Development/flutter/packages/flutter/lib/src/widgets/scroll_position_with_single_context.dart:106)
ScrollPosition.applyContentDimensions (/Users/Development/flutter/packages/flutter/lib/src/widgets/scroll_position.dart:495)
RenderShrinkWrappingViewport.performLayout (/Users/Development/flutter/packages/flutter/lib/src/rendering/viewport.dart:1754)
RenderObject.layout (/Users/Development/flutter/packages/flutter/lib/src/rendering/object.dart:1767)
RenderProxyBoxMixin.performLayout (/Users/Development/flutter/packages/flutter/lib/src/rendering/proxy_box.dart:111)
RenderObject.layout (/Users/Development/flutter/packages/flutter/lib/src/rendering/object.dart:1767)
RenderProxyBoxMixin.performLayout (/Users/Development/flutter/packages/flutter/lib/src/rendering/proxy_box.dart:111)
RenderObject.layout (/Users/Development/flutter/packages/flutter/lib/src/rendering/object.dart:1767)
RenderProxyBoxMixin.performLayout (/Users/Development/flutter/packages/flutter/lib/src/rendering/proxy_box.dart:111)
RenderObject.layout (/Users/Development/flutter/packages/flutter/lib/src/rendering/object.dart:1767)
RenderProxyBoxMixin.performLayout (/Users/Development/flutter/packages/flutter/lib/src/rendering/proxy_box.dart:111)
RenderObject.layout (/Users/Development/flutter/packages/flutter/lib/src/rendering/object.dart:1767)
RenderProxyBoxMixin.performLayout (/Users/Development/flutter/packages/flutter/lib/src/rendering/proxy_box.dart:111)
RenderObject.layout (/Users/Development/flutter/packages/flutter/lib/src/rendering/object.dart:1767)
RenderProxyBoxMixin.performLayout (/Users/Development/flutter/packages/flutter/lib/src/rendering/proxy_box.dart:111)
RenderObject.layout (/Users/Development/flutter/packages/flutter/lib/src/rendering/object.dart:1767)
RenderProxyBoxMixin.performLayout (/Users/Development/flutter/packages/flutter/lib/src/rendering/proxy_box.dart:111)
RenderObject.layout (/Users/Development/flutter/packages/flutter/lib/src/rendering/object.dart:1767)
RenderProxyBoxMixin.performLayout (/Users/Development/flutter/packages/flutter/lib/src/rendering/proxy_box.dart:111)
RenderObject.layout (/Users/Development/flutter/packages/flutter/lib/src/rendering/object.dart:1767)
RenderProxyBoxMixin.performLayout (/Users/Development/flutter/packages/flutter/lib/src/rendering/proxy_box.dart:111)
```
