### ISSUE TITLE
Scroll To Bottom Widget Showing Even When Chat Exited

### ISSUE THREAD

**Issue by ngoctranfire** [fayeed/dash_chat#77]
I'm a huge fan of this package and I love it so far for what I am using to build my application!

However, I seem to be getting a really weird error, especially with the "scroll To Bottom" widget. It seems, even after I exit my chat app, the scroll to bottom widget is still visible? This happens sometimes and I am not sure how to reproduce it. When pressing the "scrollToBottom" the following error appears since the scroll controller is trying to act on a non-visible view.
```
════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
ScrollController not attached to any scroll views.
'package:flutter/src/widgets/scroll_controller.dart':
Failed assertion: line 110 pos 12: '_positions.isNotEmpty'

When the exception was thrown, this was the stack: 
#2      ScrollController.position (package:flutter/src/widgets/scroll_controller.dart:110:12)
#3      ScrollToBottom.build.<anonymous closure> (package:dash_chat/src/widgets/scroll_to_bottom.dart:30:54)
#4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
#5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#67318
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(381.7, 716.8)
  finalLocalPosition: Offset(28.3, 27.1)
  button: 1
  sent tap down
```

**Comment by ngoctranfire** [comment]
This is already a part of #30 so I'm going to close this.
